New_feature_branch
DexLuthor/atm pull request #2
Opened 2022-08-26 16:14 UTC by ShuminArtem

added methods enterDeposit and withdraw

2022-08-26 19:54 UTC, ShuminArtem commented
added:
1. cash in 
2. withdraw money (cant be possible to withdraw more money than ATM contains)
3. fraud control

2022-08-27 10:26 UTC, DexLuthor requested changes

2022-08-27 10:26 UTC, DexLuthor commented on main.py
>      @staticmethod
using `@staticmaethod` everywhere doesn't make much sense. Watch some videos on when do we need static.
In this case we have two reasonable options:
1. don't use neither `class Atm` nor `@staticmethod`
2. use only `class Atm` (this one i'd prefer)

2022-08-27 10:26 UTC, DexLuthor commented on main.py
>          global newLogin
Does using `global` keyword everywhere has any decent purpose?

Try to read about `global` use cases

2022-08-27 10:26 UTC, DexLuthor commented on main.py
> +              'Press "3" to withdraw')
Not sure about this one: must we use `'` instead of `"`? If not wouldn't it be better to be consistent and use either `'` everywhere or `"`?

2022-08-27 10:26 UTC, DexLuthor commented on main.py
> +            Atm.deposit()
a small bug: your program will crash on stack overflow error if user inputs wrong value billion times. Come up with a better retry algorithm

2022-08-27 10:26 UTC, DexLuthor commented on main.py
> +        if int(countOfMoney) >= 10000:
Wouldn't it fail with an error when user inputs something in this vein: "you son of the bitch"?

2022-09-08 19:47 UTC, closed without merging